### ISSUE TITLE
cannot reproduce the result in RFF.ipynb

### ISSUE THREAD

**Issue by wyvern92** [hichamjanati/srf#1]
Hi, I have downloaded your ipython notebook and tried to run it for reproducing the result shown in the notebook. However, I have encountered many problems when trying to do so. For example, in RFF.ipynb, I found the rbf kernel generated is just an identity matrix. Also, errors vs sample number plot was not smooth at all. I looked at the array of errors and it just showed all 0s except for the first item. 

Would you mind helping me reproduce the result? thanks!

**Comment by wyvern92** [comment]
problem solved. should use float(D) when assign value to self.D, otherwise will get all 0 because of doing ratio.

**Comment by hichamjanati** [comment]
Hi, 

Indeed I pushed the wrong notebooks, unfortunately, I lost the "right" ones. It appears to me that I changed some parameters after I launched the plots. Here's what you should do:

1- First to have some curves in RFF-II for e.g, you must increase the length of the list: 
`indx = [2**i for i in range(1)]` (this is the list of the number of features, try smt like range(6, 12) to get good results)  
2- Increase the number of samples (takes a bit longer to run, but 100 is too low, 1000 should work fine)
3- increase `n_repeats` for less variability
4- Decrease gamma if the Kernel is the identity matrix, I remember taking those values to reproduce the results of the papers I cite

PS: The figures you saw in the notebooks took around 5-10mn to run per cell, check the .pdf in the repo to check the parameters I used in the figures
